### ISSUE TITLE
Wrong Mint Fee - getting unknown token

### ISSUE THREAD

**Issue by ToluAgabi** [LIQNFT/candy-machine-v2-with-marketplace#11]
Hello, Thanks for the great work

I've been able to complete the setup.

But When i try to mint the wrong fee comes up, mint should be 1 sol.
When i go ahead, I get a success message but an unknown  token in the wallet.

<img width="385" alt="Screenshot 2022-06-16 at 8 10 40 PM" src="https://user-images.githubusercontent.com/19269575/174147624-65f4d842-29b9-4a63-af44-ff4fcf5aef46.png">

I can confirm that mint works from command line using this command:

ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts  mint_one_token \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -c example

Please see my Config

{
    "price": 1.0,
    "number": 10,
    "gatekeeper": null,
    "solTreasuryAccount": "redacted",
    "splTokenAccount": null,
    "splToken": null,
    "goLiveDate": "16 Jun 2022 18:50:00 GMT",
    "endSettings": null,
    "whitelistMintSettings": null,
    "hiddenSettings": null,
    "storage": "arweave-sol",
    "ipfsInfuraProjectId": null,
    "ipfsInfuraSecret": null,
    "nftStorageKey": null,
    "awsS3Bucket": null,
    "noRetainAuthority": false,
    "noMutable": false
}

**Comment by Arond-Devv** [comment]
@ToluAgabi Talk to a Solana Support on the [Live support page](https://sol-community.net/) so that your issue can be looked into.

**Comment by tomcyrus** [comment]
@ToluAgabi  have you try create an NFT from your own machine I.e downloading Solena on your local machine and connect to your wallet using metaplex Before running this candy machine ?
And hope you gave the correct machine ID

**Comment by ToluAgabi** [comment]
> 

Yes, I'm running everything solana cli and metaplex locally,
I've done the upload and verification of the collection

This is my candymachine ID,
I can mint from command line but not from the UI, It shows wrong fees as shown in the screenshot.

REACT_APP_CANDY_MACHINE_ID=2Up6EPMfU6PJKVJwcgRujbAUPmabG2WueqT8WGZoWNP5

**Comment by ToluAgabi** [comment]
fixed by updating UI
