### ISSUE TITLE
I got an issue on selling page to list my nfts.

### ISSUE THREAD

**Issue by piordev555** [LIQNFT/candy-machine-v2-with-marketplace#13]
Last week, I cloned this repository and tried to make my own.
First I created candy shop on https://candy.liqnft.com/my-shop then I could see my own shop.
Then, I tried to list my own nfts on my wallet. so I copied my one of nft's address to my shop's whitelisted addresses.
After that, I could see my all of nfts created from same position like listed nft.
Also I tried do the same on vps, but it only showed one nft which I whitelisted.
So I don't know why this issue is causing on my side.

**Comment by beepsaidblue** [comment]
@egan918 if you're still experiencing issues, please ping us on Discord to troubleshoot your setup 😄
