### ISSUE TITLE
Cannot make it work on mainnet-beta (rate limited)

### ISSUE THREAD

**Issue by rxrxrxrx** [LIQNFT/candy-machine-v2-with-marketplace#6]
Hi, 

I try this repo pretty easy to setup, 
I tried to switch on mainnet,
I have an issue when I try to sell something, I can't see my collection, I get this message :(see below scerenshot)

It seems that Im not allow to fetch everything
I didnt change .env file just modified : 

REACT_APP_SOLANA_NETWORK=mainnet-beta
REACT_APP_SOLANA_RPC_HOST=https://api.mainnet-beta.solana.com

Any idea ? I just want to try to list my NFT on mainnet, then retrist NFT listing to a particular collection (still didnt try this step)

`
![bug2](https://user-images.githubusercontent.com/91226684/163827989-f54d1f14-b3d2-4444-9a7e-da01abff587c.PNG)
`

**Comment by rxrxrxrx** [comment]
I feel like "Sell" Component is not async so it fail / take a lot of time if the person has a lot of NFTs in his wallet

**Comment by beepsaidblue** [comment]
You can set REACT_APP_SOLANA_RPC_HOST=https://ssc-dao.genesysgo.net
